require 'rake/testtask'

# code style
require 'rubocop/rake_task'
RuboCop::RakeTask.new

# tests
Rake::TestTask.new do |t|
  t.test_files = FileList['test/**/test*.rb']
  t.ruby_opts = ['-W1']
end

task default: %i[rubocop test]
